name: test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "github object:"
          echo "${{ toJson(github) }}"
      - run: |
          echo "event object:"
          echo "${{ toJson(github.event) }}"
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          path: coverage/lcov.info
