name: test
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - run: npm test
      - name: Save PR number
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          mkdir -p coverage/pr
          echo ${{ github.event.number }} > coverage/pr/pr_num
          cp coverage/lcov.info coverage/pr
      - name: Upload coverage
        uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: coverage-artifact
          path: coverage/pr
          retention-days: 1 # for coverage commenting, doesn't need to be long
