name: coverage comment
on:
  workflow_run:
    workflows: [test]
    types: [completed]
jobs:
  coverage:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: read
    steps:
    - run: |
        echo "github object:"
        echo "${{ toJson(github) }}"
    - run: |
        echo "event object:"
        echo "${{ toJson(github.event) }}"
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        github_token: ${{ secrets.GITHUB_TOKEN }}
        name: coverage-artifact
    - name: Get PR number
      id: get-pr
      run: echo NUM=$(cat pr_num) >> "$GITHUB_OUTPUT"
    - uses: Nef10/lcov-reporter-action@v0.4.0
      with:
        lcov-file: lcov.info
        pr-number: ${{ steps.get-pr.outputs.NUM }}
