name: coverage comment
on:
  workflow_run:
    workflows: [test]
    types: [completed]
jobs:
  coverage:
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    runs-on: ubuntu-latest
    permissions:
      contents: read        # to read from the repo
      pull-requests: write  # to comment on the PR
      actions: read         # to download artifact
    steps:
    - run: |
        echo "github object:"
        echo "${{ toJson(github) }}"
    - run: |
        echo "event object:"
        echo "${{ toJson(github.event) }}"
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        run_id: ${{ github.event.workflow_run.id }}
        name: coverage-artifact
    # - name: Get PR number
    #   id: get-pr
    #   run: echo NUM=$(cat pr_num) >> "$GITHUB_OUTPUT"
    - uses: jameslan/lcov-reporter-action@romeovs-master
      with:
        lcov-file: lcov.info
        pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
        delete-old-comments: true
        title: 中文
        filter-changed-files: true
