name: Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of the release, need to be identical to the version in package.json
      title:
        description: Title of the release
      note:
        description: Release note in Markdown format
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ inputs.title }}
          body: ${{ inputs.note }}
          tag: v${{ inputs.version }}
          commit: ${{ github.sha }}
          token: ${{ secrets.RELEASE_TOKEN }} # Must be a PAT with repo access, to trigger following doc workflow

